### PR TITLE
Animation fix

### LINKED ISSUE #132: Shiny Animation Issue
I am trying to create a bubbleMotion chart for a Shiny application using renderAnimint, but the animation is not working.

I can get the animation to work in R/Rstudio. However, when running that same code via Shiny App it plots, but the animation will not trigger.

server.R:
```
library(shiny)
library(animint)
traditional<-readRDS("data/traditional.rds")
shinyServer(function(input, output) {
  plotBubble <- reactive({
    ggplot()+ 
      geom_point(aes(pd2_plan_cost_pmpy, percent_contribution, colour=mci, showSelected=year, size=pmpy_rx_volume),data=traditional)+
      geom_text(aes(pd2_plan_cost_pmpy, percent_contribution, colour=mci, label=mci, showSelected=year),data=traditional)+
      continuous_scale("size","area",palette=function(x){scales:::rescale(sqrt(abs(x)), c(2,20), c(0,1))},breaks=10^(4:9))+
      theme(text=element_text(colour="white"),axis.text=element_text(color="white"),plot.background=element_rect(fill = "#3475b4"),panel.background = element_rect(fill = "#3475b4"),legend.position="none",panel.grid.minor = element_line(colour="white", size=0.5)) +
      theme_animint(height = 600, width = 900)  
  })
  output$animint <- renderAnimint({ 
    list(plot1 = plotBubble(),
         time = list(variable = "year", ms = 2000),
         duration=list(year=4))
  })  
})
```

ui.R
```
library(shiny)
library(animint)

shinyUI(fluidPage(  
  titlePanel("Drug Trend"), 
  br(),  
  animintOutput("animint")  
))
```

Here is the plot within the Shiny app called from a URL:
animintbubbleplot

Clicking "Play" does not do anything...however, it properly runs through 4 years of data in R/RStudio with this same code.

Please advise.

Thanks,
Logan

### PR DESCRIPTION
**Pull request by tdhock**
maybe this will fix #132 ?

### CODE REVIEW

**Comment by tdhock** [comment]
TODO add a test for an animation inside of a shiny app

File: tests/testthat/test-shiny.R [hunk 1]
```diff
@@ -24,6 +24,66 @@ test_that("animint plot renders in a shiny app", {
   expect_true(length(circles) >= 1)
 })
 
+shiny_dir <- system.file("examples/shiny-WorldBank", package = "animint")
```
Comment (tdhock) [inline tests/testthat/test-shiny.R]: I added a new test that uses the WorldBank data viz inside a shiny app.

File: tests/testthat/test-shiny.R [hunk 2]
```diff
@@ -24,6 +24,66 @@ test_that("animint plot renders in a shiny app", {
...
+address <- sprintf("http://localhost:3148")
+
+test_that("WorldBank renders in a shiny app", {
+  Sys.sleep(10) # give shiny a second to do it's thing
+  remDr$navigate(address)
+  Sys.sleep(10)
+  ## just check that svg is displayed
+  html <- getHTML()
+  circles <- getNodeSet(html, "//div[@id='animint']//circle")
+  expect_true(length(circles) >= 1)
```
Comment (tdhock) [inline tests/testthat/test-shiny.R]: rendering works fine.

File: tests/testthat/test-shiny.R [hunk 3]
```diff
@@ -24,6 +24,66 @@ test_that("animint plot renders in a shiny app", {
...
+  expect_equal(length(node.set), 1)
+  value <- xmlValue(node.set[[1]])
+  sub("year = ", "", value)
+}
+
+test_that("animation updates", {
+  old.year <- getYear()
+  Sys.sleep(5) #wait for two animation frames.
+  new.year <- getYear()
+  expect_true(old.year != new.year)
```
Comment (tdhock) [inline tests/testthat/test-shiny.R]: animation updates do not work currently.

File: tests/testthat/test-shiny.R [hunk 4]
```diff
@@ -24,6 +24,66 @@ test_that("animint plot renders in a shiny app", {
...
+  country.labels <- getNodeSet(getHTML(), '//g[@class="geom9_text_ts"]//text')
+  sort(sapply(country.labels, xmlValue))
+}
+
+test_that("clicking selects country", {
+  old.countries <- getCountries()
+  expect_identical(old.countries, c("United States", "Vietnam"))
+  clickID("Bahrain")
+  new.countries <- getCountries()
+  expect_identical(new.countries, c("Bahrain", "United States", "Vietnam"))
```
Comment (tdhock) [inline tests/testthat/test-shiny.R]: clicking to select country doesn't work either.

File: tests/testthat/test-shiny.R [hunk 5]
```diff
@@ -24,6 +24,66 @@ test_that("animint plot renders in a shiny app", {
...
+  old.facets <- getFacets()
+  expect_identical(old.facets, c("fertility.rate", "Years"))
+  e <- remDr$findElement("class name", "selectize-input")
+  e$clickElement()
+  remDr$sendKeysToActiveElement(list(key="backspace"))
+  remDr$sendKeysToActiveElement(list("lite"))
+  remDr$sendKeysToActiveElement(list(key="enter"))
+  Sys.sleep(10)
+  new.facets <- getFacets()
+  expect_identical(new.facets, c("literacy", "Years"))
```
Comment (tdhock) [inline tests/testthat/test-shiny.R]: changing the shiny selection does update the axes.

**Comment by tdhock** [comment]
When rendering the new WorldBank example in `test-shiny.R` I get an error on the Javascript console

unrecognized-expression

**Comment by tdhock** [comment]
after clicking a year or country, no plot update, but another error on the JS console

selectized_array_undefined

**Comment by tdhock** [comment]
Seems like there is some conflict between the selectize code of @kferris10 and the shiny code. @cpsievert any ideas for a fix?

**Comment by tdhock** [comment]
all tests pass on my machine

```
testthat results ================================================================
OK: 827 SKIPPED: 0 FAILED: 0
Warning message:
The plyr::rename operation has created duplicates for the following name(s): (`showSelected`) 
> 
```
